[mypy]
python_version = 3.12
mypy_path = lib
explicit_package_bases = True
namespace_packages = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
check_untyped_defs = True
